### PR TITLE
docs: [Hackathon] add Datree policy generator README.md

### PR DESCRIPTION
**Pull request by kartikcho**
Submission for Datree Automated, a CLI tool to generate Datree policies from user input Kubernetes configurations!

- [Devpost Submission](https://devpost.com/software/shhhh) - Please take a look here for a better explanation of the project
- [GitHub Repository](https://github.com/sauravhiremath/policy-fy) - Clone to try it out for yourself!
- [Demo Video](https://youtu.be/o3AQUmHE-Ms) - Walkthrough of our project

Tag me or my teammate @sauravhiremath for any questions 🚀

### CODE REVIEW

**Comment by eyarz** [comment]
@kartikcho, I just watched the video and it looks awesome!
I can't wait to review it deeply :)

**Comment by brijeshshah13** [comment]
the idea is definitely interesting but I'm a little confused. to my understanding, a custom policy is made to ensure that the manifest files have certain standards to meet. however, as in this case, if we generate the custom policies from those manifests, doesn't that defeat the whole purpose? maybe I'm missing something here. @kartikcho @eyarz would love your inputs here.

**Comment by viploveb** [comment]
> the idea is definitely interesting but I'm a little confused. to my understanding, a custom policy is made to ensure that the manifest files have certain standards to meet. however, as in this case, if we generate from those manifests, doesn't that defeat the whole purpose? maybe I'm missing something here. @kartikcho @eyarz would love your inputs here.

+1

**Comment by roommen** [comment]
> the idea is definitely interesting but I'm a little confused. to my understanding, a custom policy is made to ensure that the manifest files have certain standards to meet. however, as in this case, if we generate the custom policies from those manifests, doesn't that defeat the whole purpose? maybe I'm missing something here. @kartikcho @eyarz would love your inputs here.

+1

**Comment by kartikcho** [comment]
We help generate custom policies based on manifest file. And assuming you have the 'correctly' designed file, you can set that as a standard for other development and future changes.

We focused on this feature, as most admins using Datree would already have k8 configs, and would be using Datree to enforce some standards - which our tool would help generate.

**Comment by viploveb** [comment]
> We help generate custom policies based on manifest file. And assuming you have the 'correctly' designed file, you can set that as a standard for other development and future changes.
> 
> We focused on this feature, as most admins using Datree would already have k8 configs, and would be using Datree to enforce some standards - which our tool would help generate.

Cool, can it work against helm charts as well?

**Comment by AvinashNayak27** [comment]
> We help generate custom policies based on manifest file. And assuming you have the 'correctly' designed file, you can set that as a standard for other development and future changes.
> 
> We focused on this feature, as most admins using Datree would already have k8 configs, and would be using Datree to enforce some standards - which our tool would help generate.

But What if The Cluster Admin Didn't design the Manifest file correctly then this tool generates different policy and when the Admin ran this policy against another Correctly designed File this Policy Fails.Am I Right??

**Comment by brijeshshah13** [comment]
> 

+1. that's exactly what i was going for

**Comment by brijeshshah13** [comment]
> > We help generate custom policies based on manifest file. And assuming you have the 'correctly' designed file, you can set that as a standard for other development and future changes.
> > We focused on this feature, as most admins using Datree would already have k8 configs, and would be using Datree to enforce some standards - which our tool would help generate.
> 
> But What if The Cluster Admin Didn't design the Manifest file correctly then this tool generates different policy and when the Admin ran this policy against another Correctly designed File this Policy Fails.Am I Right??

+1. that's exactly what i was going for

**Comment by Abhra303** [comment]
@AvinashNayak27 wrote:
> But What if The Cluster Admin Didn't design the Manifest file correctly then this tool generates different policy and when the Admin ran this policy against another Correctly designed File this Policy Fails.Am I Right??

Well, this is possible even now (Admins can write policies themselves). If an admin tests a kubernetes schema against datree default rules, all will be fine. But if he/she writes his/her own policies and tries to test, what is the guarantee that he/she has written a correct policy? In that case, all "Correctly designed File" will fail to pass.

Writing a custom policy automatically creates a risk of not following best practices.

**Comment by AvinashNayak27** [comment]
> @AvinashNayak27 wrote:
> 
> > But What if The Cluster Admin Didn't design the Manifest file correctly then this tool generates different policy and when the Admin ran this policy against another Correctly designed File this Policy Fails.Am I Right??
> 

So you are thinking that Custom Policies made using the manifest files but Custom Policies are made using the Errors we get at Production. So that other K8's Cluster Admins test their Manifest Files against this Custom Policy and prevent getting Errors at Production level

**Comment by Abhra303** [comment]
@AvinashNayak27 wrote:
> So you are thinking that Custom Policies made using the manifest files but Custom Policies are made using the Errors we get at Production. So that other K8's Cluster Admins test their Manifest Files against this Custom Policy and prevent getting Errors at Production level

You are assuming that **all** admins write policy after getting errors from production but that's not true. Not all admins do that. Experienced admins have enough knowledge to write custom policy without observing the errors from productions. Again, you can't control how admins write their policies. Some people may write their policies before "getting errors from production". Who knows, may be most people do that.

Forget about this. Let's talk about best practices. How would you know if the developers are writing policies based on the best practices? "not getting errors from production" does not imply if configurations are set according to best practices.

**Comment by AvinashNayak27** [comment]
> @AvinashNayak27 wrote:
> 
> > So you are thinking that Custom Policies made using the manifest files but Custom Policies are made using the Errors we get at Production. So that other K8's Cluster Admins test their Manifest Files against this Custom Policy and prevent getting Errors at Production level
> You are assuming that all admins write policy after getting errors from production but that's not true. Not all admins do that. Experienced admins have enough knowledge to write custom policy without observing the errors from productions. Again, you can't control how admins write their policies. Some people may write their policies before "getting errors from production". Who knows, may be most people do that.


I am not telling that all Admins write Policies.Anyone who had got issues in Production may write policies and Publish them to Datree If Datree likes the policy then they will add the policy to their Default policies Other Admins may use Datree to Test their Manifest Files So that they Don't get the Error at Production 
And Best Practices means that writing  Manifest Files without any Errors which can be checked using Datree

**Comment by Abhra303** [comment]
> I am not telling that all Admins write Policies.Anyone who had got issues in Production may write policies and Publish them to Datree If Datree likes the policy then they will add the policy to their Default policies Other Admins may use Datree to Test their Manifest Files So that they Don't get the Error at Production

I think you misunderstood how datree works. You don't have to create a Pull Request to datree to let your team-mates use those policies. Every Organization can write their own policies private to them and use those to check misconfigurations and other things standard to them using pre-commit hooks, CI etc. See the datree docs.

> Best Practices means that writing Manifest Files without any Errors which can be checked using Datree

Not at all. Take an example from git -

Often developers use `git add .` to add the changed files to git index. This does not throw any error. But this is not a recommended practice ( or best practice). This can add modified files to git index that you don't want to commit. Instead the recommended practice is to use `git add <filename>` . Both do not throw errors but only the later one is considered as a best practice.

**Comment by eyarz** [comment]
I added your project here:
https://github.com/datreeio/awesome-datree#-project

Thank you for your contribution!

**Pull request closed without merging**
