### PR TITLE
feat: add Dockerfile

### PR DESCRIPTION
**Pull request by shimont**
This is for issue #88

### CODE REVIEW

**Review by eyarz — DISMISSED** [review]
docs LGTM

**Comment by dimabru** [comment]
We're using `goreleaser` in our ci/cd flow to create binaries. Since it does support docker, I think we should keep a single source of truth when creating binaries, and use it for the docker build flow.

docs can be found here:
https://goreleaser.com/customization/docker/

**Comment by eyarz** [comment]
@dimabru is this PR still relevant?

**Comment by dimabru** [comment]
> @dimabru is this PR still relevant?

Nope

**Pull request closed without merging**
