### PR TITLE
docs: fix Grammatical and Punctuational errors

### PR DESCRIPTION
**Pull request by marooncoder09**
Hey, I have fixed grammatical errors in the README.md file

### CODE REVIEW

**Review by eyarz — APPROVED** [review]

**Comment by eyarz** [comment]
@marooncoder09 thank you for the PR!
It looks like you didn't configure your git correctly so your commit is associated with an anonymous user:
image
Please [fix that](https://crunchify.com/how-to-git-change-commit-email-and-username-fix-unrecognized-author-commit-message-on-github/) and resubmit your commit. If I will accept this commit as it is, you will not be able to get credit for your contribution.

Also, please update your commit message to follow our [commit message guideline](https://github.com/datreeio/datree/blob/staging/CONTRIBUTING.md#commit) :)

**Review by eyarz — CHANGES_REQUESTED** [review]
please fix your local git setting and update commit message

**Comment by marooncoder09** [comment]
> @marooncoder09 thank you for the PR! It looks like you didn't configure your git correctly so your commit is associated with an anonymous user: image Please [fix that](https://crunchify.com/how-to-git-change-commit-email-and-username-fix-unrecognized-author-commit-message-on-github/) and resubmit your commit. If I will accept this commit as it is, you will not be able to get credit for your contribution.
> 
> Also, please update your commit message to follow our [commit message guideline](https://github.com/datreeio/datree/blob/staging/CONTRIBUTING.md#commit) :)

Hey, thanks for pointing it out, I am actually new to open-source, so can you please guide me on how I can fix it

**Comment by marooncoder09** [comment]
@eyarz I, don't know whether I have done it right or not but, I have made one more commit ,could you please check that out

**Comment by eyarz** [comment]
You fixed your local git user name and email but you still need to re-write your first commit author details and message name:
image
From googling around, this looks like a good guide on how to fix the [author issue](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit), and this is for the [commit message name issue](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message).

Let me know if that works for you, and if you find it too difficult, don't worry have a plan B 😉

**Comment by marooncoder09** [comment]
> You fixed your local git user name and email but you still need to re-write your first commit author details and message name: image From googling around, this looks like a good guide on how to fix the [author issue](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit), and this is for the [commit message name issue](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message).
> 
> Let me know if that works for you, and if you find it too difficult, don't worry have a plane B 😉

Thanks a lot, and sorry for replying late, I was out of town, but now I am back and assure you to do it in a jiffy.

**Comment by marooncoder09** [comment]
> You fixed your local git user name and email but you still need to re-write your first commit author details and message name: image From googling around, this looks like a good guide on how to fix the [author issue](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit), and this is for the [commit message name issue](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message).
> 
> Let me know if that works for you, and if you find it too difficult, don't worry have a plan B 😉

I have completed everything listed here and but when doing the final step that is pushing the repo using 
    git push origin HEAD:master


I am getting this error.  fatal: 'c60392eac2b62145e920e743144350bb37ce087b' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
apple@Apples-MacBook-Air datree % git push origin master --force

error: src refspec master does not match any

**Comment by marooncoder09** [comment]
After completing whatever was listed I made pull request but it turned out to be something else 

I guess I need that plan B

**Comment by eyarz** [comment]
Yes, Git can be tricky sometimes...
I think the problem is that you're trying to push to master instead of staging.

Anyway, this is plan B - start from scratch:
1. stash your work (git stash) 
2. open a new branch (git checkout -b update-readme)
3. unstash your changes (git stash pop)
4. commit your changes (git commit -a README.md -m "docs: fix grammatical and punctuational error")
5. push it to remote (git push)
6. open a new PR

*I'm taking into account that your local git setting (name + email) was already fixed.
Also, if (git) stash won't work, just copy the entire content of the readme file, and past it in the readme file that you will have in the new branch.

**Comment by marooncoder09** [comment]
> Yes, Git can be tricky sometimes... I think the problem is that you're trying to push to master instead of staging.
> 
> Anyway, this is plan B - start from scratch:
> 
> 1. stash your work (git stash)
> 2. open a new branch (git checkout -b update-readme)
> 3. unstash your changes (git stash pop)
> 4. commit your changes (git commit -a README.md -m "docs: fix grammatical and punctuational error")
> 5. push it to remote (git push)
> 6. open a new PR
> 
> *I'm taking into account that your local git setting (name + email) was already fixed. Also, if (git) stash won't work, just copy the entire content of the readme file, and past it in the readme file that you will have in the new branch.

The command `git commit -a README.md -m "docs: fix grammatical and punctuational error` was giving me ` fatal: paths 'README.md ...' with -a does not make sense` so I skipped `-a README.md part` made a new PR 
and it looks something like this.
Screenshot 2021-10-08 at 1 46 33 AM


I don't know what hath happened.

**Comment by eyarz** [comment]
closing this PR because it's a (bad) duplicate of https://github.com/datreeio/datree/pull/199

**Pull request closed without merging**
