### PR TITLE
Added Greeting Github Action

### PR DESCRIPTION
**Pull request by Ayush7614**
##  Description

This PR contains

* Adds a GHA workflow to welcome new users in the project
* If PR is merged then it gives congratulations message to every participants

### CODE REVIEW

**Comment by Ayush7614** [comment]
@romanlab  Can you please have a look over the same? Thanks a lot!

**Comment by eyarz** [comment]
@Ayush7614, thank you for the PR!
I asked for some changes but please also notice that your commit message is not following [our guidelines](https://github.com/datreeio/datree/blob/staging/CONTRIBUTING.md#commit) :/

Maybe you can also implement #205 in this workflow? I haven't started working on it yet.

**Comment by Ayush7614** [comment]
> @Ayush7614, thank you for the PR! I asked for some changes but please also notice that your commit message is not following [our guidelines](https://github.com/datreeio/datree/blob/staging/CONTRIBUTING.md#commit) :/
> 
> Maybe you can also implement #205 in this workflow? I haven't started working on it yet.

@dimabru Thanks for your reply but this Github Action is different from #205 This GHA give congratulations and hurray message when anyone PR is merged

**Comment by eyarz** [comment]
Yes, I understand what this GH workflow is doing, but I don't see any value in maintaining code that is "just" for greeting new people. It will be helpful if this workflow can do more than that.

**Comment by dimabru** [comment]
Staging branch is deprecated and will soon be deleted.
Our new default branch in main.
Please change your pr to merge to main.
Thanks!!

**Comment by eyarz** [comment]
stale PR. closing.

**Pull request closed without merging**
