### PR TITLE
feat: add custom policy example

### PR DESCRIPTION
**Pull request by roommen**
Submitting the best practices policies created for datree.io policy validations for various Kubernetes objects

### CODE REVIEW

**Comment by eyarz** [comment]
@roommen, you have some really nice use cases!
The problem is that you have some rules (e.g. `06-startupProbe`, `07-imageAvoidLatest`, etc.) that will not work with resources that are creating Containers via `template` (e.g. [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment)).

You should consider updating your rules, so they will work with other types of Kubernetes resources, except just Pod:
https://hub.datree.io/multiple-property-paths

**Comment by roommen** [comment]
Thank you @eyarz for the review and comments. I'll try to work on addressing policy 6 and 7 but since it's the regular office day, not sure if my time would permit to improve this PR. Otherwise, pls ignore policies 6 and 7 for the moment

**Comment by roommen** [comment]
UPDATE: Just done with my regular office hours; should be able to spend some time on this before EOD

**Comment by eyarz** [comment]
I'm sorry, the hackathon was already over, so I can't accept new changes.
You can still update your PR, and if it passes my review, you will be an official contributor to our project :)

**Comment by roommen** [comment]
OK. It's a bit unfair that my submission will not be considered for a winning nomination as the template requirement was not mentioned in the demo video or rules.
Anyways, I do have policies for other resource types as well and not just Pods, so fingers crossed :)

**Comment by eyarz** [comment]
@roommen are still working on this PR or can I close it?

**Comment by roommen** [comment]
Nope. Pls go ahead and close the PR

**Pull request closed without merging**
