### PR TITLE
[Hackathon] Security best practices policy

### PR DESCRIPTION
**Pull request by yummyweb**
## What
This PR adds an example of a security best practices policy. This policy checks the presence of certain fields like `runAsUser` and `runAsGroup`. Using this policy, DevOps engineers are able to handle permissions and accessibility of their clusters and containers.

## Why
This policy is based off of the Kubernetes documentation and certain articles of what constitutes as security best practices. One core aspect of Kubernetes security is `securityContext`. This PR is based on `securityContext` and allows Kubernetes engineers to handle permissions and accessibilities of their clusters and the containers within it. From the documentation, `securityContext` defines and manages privileges and access control settings.

### CODE REVIEW

**Comment by eyarz** [comment]
@yummyweb, this is an excellent idea for a policy! 
From what I see, your README file lists three rules, while your policy (`policy.yaml`) contains only one rule, is this on purpose?

**Comment by yummyweb** [comment]
Yes, I was a bit apprehensive about that, let me change that.

**Comment by AvinashNayak27** [comment]
@yummyweb  I think there is an Error in your Policy Schema,It is validating every input.Please Fix the Issue
Screenshot 2021-12-11 at 6 37 45 PM

**Comment by yummyweb** [comment]
I believe the schema validator maybe incorrect since it is passing input for the sample policy. Please look at the pass.yaml and fail.yaml files I have provided and check using the cli.

CleanShot 2021-12-11 at 19 30 01@2x

**Comment by eyarz** [comment]
@yummyweb why do you apply your policy only on resources type `Pod`?
It's also relevant for other types of resources (e.g. Deployment, DaemonSet, etc.).

The **yamlschemavalidator** is working as expected.
The issue is with your YAML Schema logic. 
Please review [Example #1](https://hub.datree.io/basic-examples#c6-example-1) for reference.

**Comment by yummyweb** [comment]
Hi! My policy only applies to Pod since securityContext is set only for a Pod. It does not apply to other components (refer to Kubernetes documentation). The yaml schema validator does not seem to work since Example #1 also doesn't work. To test my policy, run it using the datree cli and test against fail.yaml.

**Comment by yummyweb** [comment]
@eyarz The yamlschemavalidator does work, it turns out the input it was checked against was invalid, since it did not have the `metadata` or `spec` property, but my policy seems to work using the datree cli and the schema validator.

**Comment by eyarz** [comment]
`securityContext` can be set for a Pod or **Container**.
Therefore, it can also be used with other resources:
https://stackoverflow.com/questions/57276023/setup-securitycontext-inside-kubernetes-deployment

**Comment by yummyweb** [comment]
I have made the changes @eyarz

**Comment by eyarz** [comment]
Thank you for participating in the Hackaton!
Unfortunately, your policy is not moving to the next step (reviewing), so I'll go ahead and close this PR.

**Comment by yummyweb** [comment]
@eyarz Why is my policy not moving forward?

**Pull request closed without merging**
