### PR TITLE
build: bump cobra version to "1.5.0"

### LINKED ISSUE #697: Bump cobra version to 1.5.0
**Is your feature request related to a problem? Please describe.**
The new version of the Cobra package has some cool features, which can be handy.

**Describe the solution you'd like**
Bump the version to 1.5.0, and make sure nothing got broken in the process.

**Additional context**
I tried using the `command.SetContext()` method (from the docs), apparently it's available only in version 1.5.0

### PR DESCRIPTION
**Pull request by CuriousCorrelation**
### Description
Bumps `cobra` version from `v1.1.3` to `v1.5.0`

### Changes
None required as far as I can tell. Build process is successful and `go run main.go` works.

### Issue
Closes  #697

### CODE REVIEW

**Review by aroramrinaal — DISMISSED** [review]

**Comment by myishay** [comment]
Hi @aroramrinaal , thanks for your contribution!

Regarding the PR title and commits, we are trying to follow [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0/#specification) for the commits and `perf:` prefix doesn't apply to it. I suggest using `build:` instead.

In addition, I see the tests don't pass in the travis build.

**Comment by CuriousCorrelation** [comment]
@myishay I think you wanted to ping me :wave:

I think I missed those zsh completion changes because I ran tests on some other folder. This new patch should take care of that!

For reference: https://github.com/spf13/cobra/pull/1690

According to the PR

```
#compdef _<command> <command>
```
> enabled completions for both <command> and _<command>, but _<command> is the completion function itself and should not be completed

I have fixed the commit messages. Also divided changes:

1. `go.sum` and `go.mod` in `build:`, and 
2. `cmd/completion` in `fix:`

Let me know if something needs a second look

**Comment by myishay** [comment]
I also updated the PR title to match the commit message

**Comment by myishay** [comment]
> @myishay I think you wanted to ping me 👋

You are correct! I realized it only now 😅
so @CuriousCorrelation thank _you_ for your contribution 😁

**Comment by CuriousCorrelation** [comment]
> You are correct! I realized it only now 

No worries at all!

Everything should be good to go, although feel free to let me know if there are any changes I should make.

**Comment by myishay** [comment]
LGTM!
I have updated the branch to the latest changes and will merge this soon

**Review by myishay — APPROVED** [review]

**Pull request merged**
