### PR TITLE
Fixed the installation script

### LINKED ISSUE #195: Installation script continues even if download fails
**Describe the bug**
The install script continues execution even if there are errors in the download process and the download fails

**To Reproduce**
1. curl https://get.datree.io | /bin/bash
2. interrupt internet(disable wifi during download)
3. See error

**Expected behavior**
Error message and non-zero exit code

**Screenshots**

WhatsApp Image 2021-10-10 at 10 28 46

**Desktop (please complete the following information):**
 - OS: Any

**Datree version (run `datree verion`):**
 - Version: Any

### PR DESCRIPTION
**Pull request by ashish-ad**
### Working on issue #195 
can test by using the command "Screenshot from 2021-10-17 03-51-30" before the command "curl -sL $DOWNLOAD_URL -o $OUTPUT_BASENAME_WITH_POSTFIX" and then can test the file which shows the exit code and the command from where the script got terminated.
PS: I have attached a SS while I was testing.

### CODE REVIEW

**Review by romanlab — CHANGES_REQUESTED** [review]
@ashish-ad the code looks great but please follow our contribution [guide](https://github.com/datreeio/datree/blob/staging/CONTRIBUTING.md#-submission-guidelines), specifically our [commit message standards](https://github.com/datreeio/datree/blob/staging/CONTRIBUTING.md#commit)

**Comment by romanlab** [comment]
Closes #195

**Comment by ashish-ad** [comment]
So should I commit again with 'git commit --all' that is without the message if u want I can do it?!

**Comment by romanlab** [comment]
> So should I commit again with 'git commit --all' that is without the message if u want I can do it?!

I don't think it'll work because you already pushed. You need to `git commit --amend` the commit message. You can use [this](https://stackoverflow.com/questions/8981194/changing-git-commit-message-after-push-given-that-no-one-pulled-from-remote) for reference.

**Comment by romanlab** [comment]
Also, the trap doesn't work as expected:

It prints out the final command anyway.
image


I think the `set -e` is a good enough solution for the issue so you can remove the rest of the changes and it'll still be a good fix.

**Comment by ashish-ad** [comment]
I can make changes like I can set if conditional statement if the exit code is 0 then not to print the statement. What's ur suggestion. And about the commit message the type should be 'fix' and can the message be like 'change in install script' or suggestions please.

**Comment by romanlab** [comment]
Yeah, the message should be `fix: ` and the text. You can either make a conditional or remove the whole thing that uses `trap`. It's your call, both are fine with me

**Comment by ashish-ad** [comment]
Hey @romanlab, I have made changes is this fine can u just review it again and if any changes are needed to be done can suggest me.

**Comment by eyarz** [comment]
@ashish-ad your fork is out-of-sync. You are trying to push old changes to our [README file](https://github.com/datreeio/datree/pull/204/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).
Please [sync your fork](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) with the upstream repo.

**Review by ashish-ad — COMMENTED** [review]
@eyarz I have rebased my branch please have a look

**Comment by eyarz** [comment]
@ashish-ad but you didn't submit the changes.
Your PR still contains changes in the [README file](https://github.com/datreeio/datree/pull/204/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

The easiest way to fix it is by opening a new PR with only the relevant changes 😅

**Comment by ashish-ad** [comment]
creating a new branch and pull request.

**Pull request closed without merging**
