### PR TITLE
feat: bump golang version to 1.18

### LINKED ISSUE #574: Bump golang to v1.18
**Is your feature request related to a problem? Please describe.**
We need to stay up to date with golang versions.
Failing to do so will cause us to be behind homebrew build version (which they keep up to date) and can potentially fail future versions from being deployed on homebrew

**Describe the solution you'd like**
Support golang v1.18 :)

### PR DESCRIPTION
**Pull request by amustaque97**
Fixes: #574

### CODE REVIEW

**Comment by TzlilSwimmer123** [comment]
Hi @amustaque97 :)
Thanks for your contribution! 👏 
We will check it out in the next couple of days

**Review by TzlilSwimmer123 — CHANGES_REQUESTED** [review]
Hi @amustaque97 thanks for your time :)

There are several places which the go version are 1.17 and we need to update them also to 1.18. You can search the codebase with "1.17" and see where an update is needed

**Comment by TzlilSwimmer123** [comment]
Hello @amustaque97, thanks

I tried to run our tests and one of them fails. If you will run `make test` you will see it, can you please take a look?

**Comment by TzlilSwimmer123** [comment]
Hi again, @amustaque97 I see that after merging from main the tests pass. Interesting, I will keep with the testing the code and see things are ok. Then I will approve it, thanks!

**Comment by TzlilSwimmer123** [comment]
Hello @amustaque97 I didn't forget about it, will be merged in the begging of upcoming week

**Review by TzlilSwimmer123 — APPROVED** [review]
Thanks @amustaque97

**Review by TzlilSwimmer123 — APPROVED** [review]
Thanks @amustaque97

**Review by hadar-co — APPROVED** [review]

**Pull request merged**
