### PR TITLE
feat: created custom policy in example based on container and security

### PR DESCRIPTION
**Pull request by AdeshKhandait**

### CODE REVIEW

**Comment by eyarz** [comment]
@AdeshKhandait, you have some really nice use cases!
The problem is that you have some rules that will not work with resources that are creating Containers via `template` (e.g. [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment)).

You should consider updating your rules, so they will work with other types of Kubernetes resources, except just `Pod`:
https://hub.datree.io/multiple-property-paths

**Comment by AdeshKhandait** [comment]
> @AdeshKhandait, you have some really nice use cases! The problem is that you have some rules that will not work with resources that are creating Containers via `template` (e.g. [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment)).
> 
> You should consider updating your rules, so they will work with other types of Kubernetes resources, except just `Pod`: https://hub.datree.io/multiple-property-paths

Hey, @eyarz
Thanks for your valuable reply I am glad that that these are nice.
**_Sir Can you please give any resource for that template in the which the container are build so that I can update my rules_**
By way it very wonderful experience building these policy.
**_I am really looking forward to contribute more apart from these hackathon._**

**Comment by eyarz** [comment]
I'm happy to hear that you enjoyed the Hachakaton!
Unfortunately, the Hachakaton was already over, so I can't accept new changes.
You can still update your PR, and if it passes my review, you will be an official contributor to our project :)

**Comment by AdeshKhandait** [comment]
> I'm happy to hear that you enjoyed the Hachakaton! Unfortunately, the Hachakaton was already over, so I can't accept new changes. You can still update your PR, and if it passes my review, you will be an official contributor to our project :)

Its fine, I not just to doing for the Hackathon, what I care more about its my contribution to open source that what more matters to me, Inspite of hackathon is over i will continue to contribute to open source. Its will great if won but if not total fine i still continue to contribute..

_**Please share any source to me so that i can make necessary changes in rules so that my PR can merge in the project**_

**Comment by eyarz** [comment]
Happy to hear that, we would love to accept your PR once you will update your rules :)
All the needed resources are mentioned in [my comment](https://github.com/datreeio/datree/pull/335#issuecomment-991963528).

You can also review other policies that others created with similar rules to see what needs to be updated in your code.
If you need more help, feel free to reach out on our Slack channel.

**Comment by eyarz** [comment]
@AdeshKhandait are you still working on this PR or can we close it?

**Comment by AdeshKhandait** [comment]
> @AdeshKhandait are you still working on this PR or can we close it?
i'm working on it but Actually i was stuck in my internship process so unable to work on it i will complete it by next week. Thank you

**Review by Mitumaru — APPROVED** [review]

**Pull request closed without merging**
