### PR TITLE
Corrected spelling mistake

### PR DESCRIPTION
**Pull request by saikatbishal**
Corrected the spelling of kubernetes on line number 24.

### CODE REVIEW

**Comment by saikatbishal** [comment]
corrected spelling mistake on readme file.

**Comment by eyarz** [comment]
@saikatbishal, thank you for the PR!
Please fix your commit message to match [our commit message guideline](https://github.com/datreeio/datree/blob/staging/CONTRIBUTING.md#commit).

**Comment by saikatbishal** [comment]
### refractor : change spelling mistake in readme line 24

**Comment by eyarz** [comment]
@saikatbishal here is a guide on [how to change your commit message](https://linuxize.com/post/change-git-commit-message/#pushed-commit).
please be noted that it should be `doc: <commit-message>` and not `refractor: <commit-message>`

**Pull request closed without merging**
