### PR TITLE
refactor: move deploymentConfig into internal folder

### LINKED ISSUE #436: Move deploymentConfig into internal folder
**Describe the solution you'd like**

The `interna`l directory is the place to put your private packages. Code that is placed in an `internal` directory couldn’t be imported by external project. 

**Requirements**
Golang basic level.

### PR DESCRIPTION
**Pull request by vbh**
Closes #436

### CODE REVIEW

**Comment by myishay** [comment]
@vbh LGTM, updating your branch

**Review by myishay — DISMISSED** [review]

**Comment by myishay** [comment]
@vbh we will merge your changes in the next few days 😊

**Review by dimabru — CHANGES_REQUESTED** [review]
hi @vbh,
sorry for taking our time with your pr. we just need you to fix the linter error
`Error: "github.com/datreeio/datree/internal/deploymentConfig" imported but not used (typecheck)`
as soon as you're done, add a comment and tag someone from our team and we will merge it

**Comment by dimabru** [comment]
@vbh 
Thanks for making the required changes
As you can see we are advancing with other changes and it's causing other prs (like this one) to get conflicts relatively fast so I will try to fix them myself and push to your branch in the next few hours so we can finally merge this pr

Thanks for being patient :)

**Review by dimabru — APPROVED** [review]

**Pull request merged**
