### PR TITLE
docs: slack button

### PR DESCRIPTION
**Pull request by shimont**
Adding slack button

### CODE REVIEW

**Comment by eyarz** [comment]
I think it is getting lost there with all the other badges :/
maybe do something like that:
image
https://github.com/CircuitVerse/CircuitVerse#community

**Comment by shimont** [comment]
@eyarz WDYT?

**Comment by eyarz** [comment]
much better but the logo is pixeled (because you enlarged the image) and the button can be smaller 😅
image

**Comment by shimont** [comment]
@eyarz is it better now?

**Comment by eyarz** [comment]
now it's perfect but please fix the logo (datree)

**Comment by shimont** [comment]
What seems to be the issue with the logo?

**Comment by shimont** [comment]
> now it's perfect but please fix the logo (datree)

What seems to be the issue with the logo?

**Comment by eyarz** [comment]
> much better but **_the logo is pixeled (because you enlarged the image)_** and the button can be smaller 😅 image

@shimont

**Comment by shimont** [comment]
@eyarz please review now

**Review by eyarz — APPROVED** [review]

**Pull request merged**
