### PR TITLE
docs: Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by romanlab**
docs: Update CONTRIBUTING.md

### CODE REVIEW

**Review by eyarz — COMMENTED** [review]
what do you mean by "correct Project setting(datree)"?

**Comment by romanlab** [comment]
Need to choose the datree project, this way, it'll automatically be added to the project board.
It's right under labels

**Comment by eyarz** [comment]
I just checked it and only users from Datree can assign it to a project

**Comment by romanlab** [comment]
good catch

**Pull request closed without merging**
