### PR TITLE
docs: [Hackathon] add vscode extension README.md

### PR DESCRIPTION
**Pull request by SuyashSonawane**

### CODE REVIEW

**Comment by eyarz** [comment]
Good job! 🚀

**Comment by theowlet** [comment]
Weren't we supposed to make policy?

**Comment by SuyashSonawane** [comment]
> Weren't we supposed to make policy?

I reached out to organizers about my idea and they accepted it 🚀

**Comment by eyarz** [comment]
> Weren't we supposed to make policy?

@theowlet it's also listed in the [instructions](https://github.com/datreeio/datree/tree/main/examples#warning-important-notes).

**Comment by AvinashNayak27** [comment]
Bro found your project Awesome But  What if I wanted to add Flags to the Datree test command Such as `--ignore-missing-schemas` `--schema-version` etc... Hope you find a way for that

**Comment by SuyashSonawane** [comment]
> Bro found your project Awesome But What if I wanted to add Flags to the Datree test command Such as `--ignore-missing-schemas` `--schema-version` etc... Hope you find a way for that

Thanks, Avinash, currently it does have support for schema version (https://youtu.be/SjLCTpX0bxY?t=125), ignore-missing-schemas can be added, thanks for the suggestion 💯

**Comment by eyarz** [comment]
I added your project here:
https://github.com/datreeio/awesome-datree#-project

Thank you for your contribution!

**Pull request closed without merging**
